### ISSUE TITLE
Need a different procedure to build openeo-backend-validator inside a Docker container

### ISSUE THREAD

**Issue by jona159** [GeoSoftII2020-21/TestRepo#1]
We tried to create a [Workflow](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/.github/workflows/backend-validator.yml) to build and use the openeo-backend-validator inside of a docker Container via `docker exec` . However after several attempts this seems to overcomplicate everything and does not appear to be the proper way to do it.

**Comment by nuest** [comment]
I find the naming of the steps a bit confusing. Isn't "Docker Run" going through the same steps as "Change Directory"?

I would suggest not to run the validator itself in a container.

A few questions:

- `matrix.platform`: you just have one platform you need, right? Dropping this might increase readability of the workflow configuration
- Why do you need to login to the container registry?
- Does this line https://github.com/GeoSoftII2020-21/TestRepo/blob/main/.github/workflows/backend-validator.yml#L112 run the validator? If you run it locally, what are the exit codes for success/failure? Is there no log output?
