### ISSUE TITLE
Package devtools cannot be installed (Workflow R-Client) 

### ISSUE THREAD

**Issue by jona159** [GeoSoftII2020-21/TestRepo#2]
The package _devtools_ fails to install in the [R-Client Workflow](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/.github/workflows/r-client.yml), which is a known problem on ubuntu. However none of the solutions i found worked in this case : [Action](https://github.com/GeoSoftII2020-21/TestRepo/runs/1722351748?check_suite_focus=true). 
( See for example: 
https://stackoverflow.com/questions/20923209/problems-installing-the-devtools-package
https://stackoverflow.com/questions/31114991/installation-of-package-devtools-had-non-zero-exit-status-on-ubuntu
https://community.rstudio.com/t/usethis-github-actions-failing-with-error-there-is-no-package-called-devtools/85263 )

**Comment by m-mohr** [comment]
If this is an R client issue, I'd propose to better open it directly in the R client issue tracker. The R client devs won't see it here.
