### ISSUE TITLE
grep -v unable to find given value in backend-validator output (json)

### ISSUE THREAD

**Issue by a2beckj** [GeoSoftII2020-21/TestRepo#3]
We try to find a "Error" or "Invalid" Value within the output of our backend-validator result with grep. 
In fact there are Errors in the result but grep throws a 0, instead of a 1. See this [Action](https://github.com/GeoSoftII2020-21/TestRepo/runs/1723363281?check_suite_focus=true) or this [Action when exported and then imported as json](https://github.com/GeoSoftII2020-21/TestRepo/runs/1723482148?check_suite_focus=true)

**Comment by m-mohr** [comment]
I can't see any grep calls in the mentioned logs?! Without the command you are running it's not reproducible for me.

**Comment by a2beckj** [comment]
![image](https://user-images.githubusercontent.com/18323856/105177756-66b62f80-5b27-11eb-8f93-2f7cf864cdca.png)
This is the Code we execute from within the action, but our output is this: [action](https://github.com/GeoSoftII2020-21/TestRepo/runs/1734216793?check_suite_focus=true). The output is 0, but in fact it should be 1

**Comment by m-mohr** [comment]
-v inverts the search. Check the docs whether that is what you are looking for, it doesn't sound like that.

**Comment by a2beckj** [comment]
We are refering to an example given by Daniel Nüst
![image](https://user-images.githubusercontent.com/18323856/105180606-14770d80-5b2b-11eb-8b78-aa1804e75911.png)
In fact we'd like to have a solution that delivers a boolean o.e. if a given keyword is (not) located in a given (json-)file

**Comment by m-mohr** [comment]
Could you please provide a reproducible example? I.e. an example file and all the commands you have tried yourself with the results (as text, not image)?

**Comment by a2beckj** [comment]
After a long video call with geosoft2-staff, we managed to solve that issue finally. Here comes the (only working) solution. Might also help you if you ever encounter such a problem: 
![image](https://user-images.githubusercontent.com/18323856/105198245-c1f31c80-5b3d-11eb-92b5-c08dfc8fdb68.png)
Thanks for your help though :)
