### ISSUE TITLE
Can't reach server with curl or requests

### ISSUE THREAD

**Issue by a2beckj** [GeoSoftII2020-21/TestRepo#4]
We cannot reach the server created with docker compose in Github Action. 
The server can be reached locally by calling http://localhost:80/api/v1. It is not empty. 
What we already tried (among various other things):
curl http://0.0.0.0:80/api/v1 -> curl: (52) Empty reply from server
requests.get('http://0.0.0.0:80/api/v1') -> Error: Process completed with exit code 2.

The docker images have been created successfully prior to that:
![image](https://user-images.githubusercontent.com/18323856/105341876-eacbee00-5bdf-11eb-9d59-3f3ea9358d29.png)

Can you give us any advice on what to try else?
Is this maybe a docker-compose configuration problem? (see docker-compose.yml attached as txt)
[docker-compose.txt](https://github.com/GeoSoftII2020-21/TestRepo/files/5848789/docker-compose.txt)

**Comment by nuest** [comment]
You're exposing port 80 from the different contains and they get assigned random ports - is that desired?? I suggest that _only_ the `frontend` container exposes a port. 

Also, the process contains seems to have an error in your screenshot.

Other than that, port `80` is in the protected port range, maybe try a larger port, `8080` ?

**Comment by jona159** [comment]
We tried many different port mapping combinations, but we still got the same syntax error message regarding line 50 in our [workflow](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/.github/workflows/EndToEnd.yml) for all of them, so this seems to be unrelated: 

![syntax_error](https://user-images.githubusercontent.com/65068389/105404830-b6315400-5c2a-11eb-9c11-f1bf10302ad0.png)

**Comment by jona159** [comment]
We still run into the same problem with port 8080, curl either responds with 
* curl: (56) Recv failure: Connection reset by peer 
* curl: (52): Empty reply from server

Pinging from within the container also did not work.

We reached the server in [one case](https://github.com/GeoSoftII2020-21/TestRepo/runs/1750947377?check_suite_focus=true), but unfortunately i was not able to reproduce this.

**Comment by nuest** [comment]
Looking at [this run](https://github.com/GeoSoftII2020-21/TestRepo/runs/1761034269?check_suite_focus=true) it seems like `e2e.py` works as expected now. Can you confirm?

**Comment by a2beckj** [comment]
We can reach the server by accessing the larger port now. The server developers had to adjust their server.py scripts also though.

**Comment by nuest** [comment]
Great!

So, the problem was that the server process did not accept connections on all ports?

It would be great if you could post a link here to the commit or PR that solved the issue in the server repository.

**This means that JS client and R client should also be testable via CI, correct?**

**Comment by a2beckj** [comment]
No, the js-client and the r-client are still unable to connect to our backend as described in [this issue](https://github.com/GeoSoftII2020-21/TestRepo/issues/5), although the according docker containers started and connected successfully (according to our interpretation)

This issue was just dealing with the problem that we could not start the containers properly first (,that we basically need for various tests). Now this seems to work, but we still cannot run any end to end test because the server infrastructure is still too buggy up to now.

**Comment by ghost** [comment]
We changed the port in the compose File and the internal port. The python server was listening at port 80. It was set in the Compse file as 80:80, now its 8080:8080. 
https://github.com/GeoSoftII2020-21/GeoSoftII_Frontend/commit/d5f32b991cb17b5a61cc191d27074915f4a81e57
https://github.com/GeoSoftII2020-21/GeoSoftII_Projekt/commit/648fd9c6a73074cca8e531a67b4100b76006812c

**Comment by nuest** [comment]
Hmm.. OK. Ideally this value is configurable. The outside port for local deployments should still be `80`.

**Comment by a2beckj** [comment]
As another possible solution for this:
We also changed the 'depends_on:' parameter in the docker-compose.yml, becaue in actions it seems to be very important that images start in a certain sequence to be able to access the server.
