### ISSUE TITLE
R-Client Instructions and Documentary

### ISSUE THREAD

**Issue by jona159** [GeoSoftII2020-21/TestRepo#7]
To connect to our backend locally via the openEO R-Client follow these steps: 

* Make sure to have the package _devtools_ installed and opened by using the commands:

  *  `install.packages("devtools")` and `library(devtools)`
      
* install the R-Client module : `devtools::install_github(repo="Open-EO/openeo-r-client",dependencies=TRUE)`
  
  * __maybe you will have to add `force=TRUE`__
  
* If you have trouble following these steps please also have a look at [R-Client](https://openeo.org/documentation/1.0/r/#installation) or [R-Client github](https://github.com/Open-EO/openeo-r-client) 
 
* Afterwards use the commands as shown in the screenshots: 
![R-Client_establish_connection](https://user-images.githubusercontent.com/65068389/105851070-dc684280-5fe2-11eb-880e-faf789dd41fb.png)

![Collections](https://user-images.githubusercontent.com/65068389/105851274-23eece80-5fe3-11eb-906a-aee2c42dbb69.png)

![processes_ndvi](https://user-images.githubusercontent.com/65068389/105851326-36690800-5fe3-11eb-9a36-c5f05223e475.png)

![mean_sst_process](https://user-images.githubusercontent.com/65068389/105851386-4bde3200-5fe3-11eb-9c06-cce055ecbf01.png)

![save_result_process](https://user-images.githubusercontent.com/65068389/105851606-9cee2600-5fe3-11eb-927d-d407e9ffe57e.png)

![load_collection_process](https://user-images.githubusercontent.com/65068389/105851623-a24b7080-5fe3-11eb-8853-ee26922fdd74.png)

![collections_and_processes](https://user-images.githubusercontent.com/65068389/105851659-abd4d880-5fe3-11eb-90dc-9c3f81bae2f1.png)

**Comment by nuest** [comment]
These are too many manual steps. Even if the client test does not work with the CI system, there should be actual tests.

You could use [`testthat`](https://testthat.r-lib.org/) or [`tinytest`](https://github.com/markvanderloo/tinytest) for this.

The local execution of these tests should require not more than the following (if `testthat` is used):

```bash
docker-compose up ...

# optional: Install R packages
# Rscript install.R

R -e "devtools::test()"
```

**Comment by jona159** [comment]
I am not sure what is meant with _too many manual steps_ . Do you mean i should provide an R script in the github repository that you can then download and execute? 

Regarding the tests, i am currently working on that, can i provide screenshots like down below aswell or is something else required ? 

![test_that_check_collections](https://user-images.githubusercontent.com/65068389/105873137-73d98f80-5ffb-11eb-8025-959ee5b9db69.png)

**Comment by nuest** [comment]
If you have a scripted process, you don't need to provide screenshots of all the steps. You can also copy over the console output, that is more accessible than screenshots.

If you want to add full log files, collapsible code blocks are helpful: https://github.com/dear-github/dear-github/issues/166#issuecomment-236342209

**Comment by jona159** [comment]
Is it sufficient to provide the script with an integrated Test Suite like this: [R-Client Skript](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/R-Client%20Script.R) ?

**Comment by nuest** [comment]
Ja, das ist OK. Bitte die `install.packages(..)`  nur ausführen, wenn das Paket noch nicht installiert ist.

Klappt das mit diesem Skript denn dann auch in der CI ?

**Comment by jona159** [comment]
Es scheitert im Moment leider noch beim Versuch die Verbindung herzustellen:

![connection_failed](https://user-images.githubusercontent.com/65068389/106578843-42ebe400-6540-11eb-95c3-868ff39b064e.png)

**Comment by nuest** [comment]
Ist das nicht gefixt worden für die anderen Tests? Was unterscheidet den R client von den anderen clients?

**Comment by a2beckj** [comment]
Hallo, 
wir wissen leider nicht, wo das Problem liegt. Wir starten die Container genauso, wie beispielsweise für den BackendValidator und die EndToEnd Tests, Dort funktioniert es reibungslos. Wir erhalten die Fehlermeldung, wenn wir versuchen das Backend über dieses Kommando aufzurufen:

> name: Load openEO package
>         run:  R -e 'library(openeo); host_url="http://0.0.0.0:8080/"; api_versions(host_url); gee = connect(host = host_url, version="1.0.0"); processes=list_processes(); print(names(processes))'

Der Fehler ist dann folgender: 

> Failed to connect to localhost port 80: Connection refused

Wir verstehen nicht, warum der r-client versucht uns nach wie vor mit dem Port 80 zu verknüpfen und schaffen es nicht das Problem zu lösen. Wir haben auch schon mehrere Lösungsanzätze probiert - leider alles ohne Erfolg. Bei den anderen tests ist der Port 8080 problemlos und korrekt zu erreichen. Wir versuchen das backend genauso zu erreichen, wie in diesem [issue](https://github.com/Open-EO/openeo-r-client/issues/60) vorgeschlagen bzw. so wie es auch lokal bei uns funktioniert. Nun sind wir mit unserem Latein am Ende. 

Hättest du noch einen Vorschlag oder dürfen wir nun analog zum js-client auch für den r-client auf ein lokal ausführbares Testszenario verweisen (zumal es nun zeitlich auch etwas knapp wird und wir wirklich schon viel Zeit und Energie in das Aufsetzen des R-Clients gesteckt haben)?

**Comment by nuest** [comment]
Habt ihr andere IPs probiert (`localhost`, `127.0.0.1`) ?

Außerdem wieder eine Inkonsistenz: Ihr baut eine Verbindung auf port `8080` auf, und die Fehlermeldung erwähnt port `80`.

Vielleicht unterstützt der client keine Port-Nummern? Habt ihr lokal auch mit port `8080` getestet?

**Comment by jona159** [comment]
Mit anderen IPs stoßen wir auf dasselbe Problem.

Lokal funktioniert es auf port 80, in den github Actions lässt sich die Verbindung zum Teil herstellen, wie in [dieser Action](https://github.com/GeoSoftII2020-21/TestRepo/runs/1820837484?check_suite_focus=true) mit [dieser docker-compose](https://github.com/GeoSoftII2020-21/TestRepo/blob/main/docker-compose_80.yml) (die jedoch alte images benutzt), wobei es allerdings in demselben workflow in dem [ubuntu-latest devel job](https://github.com/GeoSoftII2020-21/TestRepo/runs/1820837468?check_suite_focus=true) nicht funktioniert. Da wir die Verbindung mit den Github Actions nicht zuverlässig herstellen können wäre unser Vorschlag daher eine Anleitung zum lokalen Aufsetzen des R-Clients zu schreiben

**Comment by jona159** [comment]
Die Verbindung lässt sich nun auch in den Github Actions herstellen

**Comment by nuest** [comment]
@jona159 Was war das Problem?

**Comment by a2beckj** [comment]
Hey @nuest ,
good news. We decided to change the port of the backend from 8080, back to 80. The server team also changed that port in their configurations. Now the js-client, as well as the r-client, work with the actions :)
We no longer need the workarounds now, and will close our related issues.
