### ISSUE TITLE
JS-client instructions and documentary

### ISSUE THREAD

**Issue by a2beckj** [GeoSoftII2020-21/TestRepo#8]
**This issue is meant to be as a local workaround for this [issue](https://github.com/GeoSoftII2020-21/TestRepo/issues/5).**

1. Start the given docker containers with docker-compose up. (You can find the yml [here](https://github.com/GeoSoftII2020-21/GeoSoftII_Projekt/tree/Docker-compose).)
2. Save the html an js files given [here](https://github.com/GeoSoftII2020-21/TestRepo/tree/main/js-client) in a local directory.
3. Open the html file in a Browser (Chrome recommended).
4. After 5 seconds you will be able to see the test results evaluated by QUnit.

![image](https://user-images.githubusercontent.com/18323856/105978271-a5ea0080-6092-11eb-9603-0b16cfeec127.png)

**Comment by nuest** [comment]
I suggest you start the instructions with "`git clone` this repository" - so you can be sure that the user has all the files in the latest version.

**Comment by a2beckj** [comment]
Hey @nuest , 
good news. We decided to change the port of the backend from 8080, back to 80. The server team also changed that port in their configurations. Now the js-client, as well as the r-client, work with the actions :)
We no longer need the workarounds now, and will close our related issues.
